<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>..\..\src\ServiceBusEmulatorExplorer.App\Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="..\..\src\ServiceBusEmulatorExplorer.App\Assets\AppIcon.png" Link="Assets\AppIcon.png" />
  </ItemGroup>
</Project>
